name: Screenshot

concurrency:
  group: screenshot-${{ github.ref }}
  cancel-in-progress: true

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/ms-playwright
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-
      - run: yarn --frozen-lockfile
      - run: yarn viteshot -p
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: "**/__screenshots__/"
